package br.com.senai.exceptions;

public class Exemplo3Exceptions {
	public static void main(String[] args) {
		int vetor[] = {10,30,60};
		int a = 30, b = 0, c = 0;
		String nome = null;
		
		try {
			System.out.println(nome.equals("Vinicius"));
			System.out.println("Vetor posição 3:" + vetor[3]);
			c = a / b;
		} catch (ArithmeticException e) {
			System.out.println("Erro de divisão por zero !");
			e.printStackTrace();
		} catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("Vetor fora de faixa !");
			e.printStackTrace();
		} catch(NullPointerException e) {
			System.out.println("Esqueceu da instância do objeto !");
			e.printStackTrace();

		}
	}
	
}
